/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.parchmentmc.lodestone;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class LodestonePlugin implements Plugin<Project> {
    public void apply(Project project) {
        LodestoneExtension extension = project.getExtensions().create("lodestone", LodestoneExtension.class, project);
    }
}
