/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.parchmentmc.lodestone;

import org.gradle.api.Action;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.gradle.api.plugins.ObjectConfigurationAction;

public class LodestonePlugin implements Plugin<Project> {
    public void apply(Project project) {
    }
}
